GET http://localhost:5001/api/6503a1fc1372d11914dd4655

###

POST http://localhost:5001/api
Accept: application/json
Content-Type: application/json

{
    "name": "onyeka"
}
###
PUT http://localhost:5001/api/6503a1fc1372d11914dd4655
Accept: application/json
Content-Type: application/json

{
    "name": "onyeka dav"
}

###
DELETE http://localhost:5001/api/6503a1fc1372d11914dd4655
