GET http://localhost:5001/api/onyeka

###

POST http://localhost:5001/api
Accept: application/json
Content-Type: application/json

{
    "name": "onyeka"
}
###
PUT http://localhost:5001/api/onyeka dav
Accept: application/json
Content-Type: application/json

{
    "name": "onyeka david"
}

###
DELETE http://localhost:5001/api/onyeka david
